import { Difficulty } from '@/types';
import { SeedTopic } from './seed-data';

interface RawAiTopic {
  category: string;
  title: string;
  difficulty: Difficulty;
  priority: number;
  summary: string;
  intuition: string;
  pitfalls: string;
  notes: string;
  code?: string;
  url?: string;
}

const slugify = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

const C1 = '1. LLM Fundamentals';
const C2 = '2. Prompt & Context Engineering';
const C3 = '3. RAG & Vector Search';
const C4 = '4. Agent Fundamentals';
const C5 = '5. Tools, MCP & Frameworks';
const C6 = '6. Full-Stack AI Apps';
const C7 = '7. Evals & Observability';
const C8 = '8. Safety & Security';
const C9 = '9. LLMOps & Production';
const C10 = '10. AI-Assisted Engineering';
const C11 = '11. AI System Design';
const C12 = '12. Capstone Projects';

const RAW: RawAiTopic[] = [
  // ---------------- 1. LLM Fundamentals ----------------
  {
    category: C1,
    title: 'Tokens, Context Windows & Cost Math',
    difficulty: 'Easy',
    priority: 1,
    summary: 'How text becomes tokens, what the context window limits, and how to estimate latency and cost per request.',
    intuition: 'Models read and bill in tokens (about 4 English characters, roughly 0.75 words). Cost = input_tokens x input_price + output_tokens x output_price, and output tokens cost several times more. Chat history is re-sent every turn, so cost per turn grows with conversation length.',
    pitfalls: 'Assuming the advertised context size is usable quality-wise (long contexts degrade recall in the middle); forgetting that tool results and system prompts also count; not setting max_tokens.',
    notes: '### Tokens & Context\n- Tokenizer is model-specific (BPE variants); count with the provider tokenizer, never by characters.\n- Context window = input + output tokens combined.\n- Prefill (reading the prompt) is fast and parallel; decode (generating) is sequential, so latency ~ TTFT + output_tokens x time_per_token.\n- Budget every request: system prompt + history + retrieved chunks + tool results + reserved output.\n- Trim strategies: sliding window, summarise old turns, drop stale tool results.\n\n### Back-of-envelope\n10k input + 1k output tokens at $3/M in and $15/M out = $0.03 + $0.015 = $0.045 per call. At 100k calls/day that is $4,500/day, which is why caching and routing matter.',
    code: 'function estimateCostUsd(inTok: number, outTok: number, pricePerMIn: number, pricePerMOut: number) {\n  return (inTok / 1e6) * pricePerMIn + (outTok / 1e6) * pricePerMOut;\n}\nconsole.log(estimateCostUsd(10_000, 1_000, 3, 15)); // 0.045',
  },
  {
    category: C1,
    title: 'How LLMs Work: Transformers, Attention & KV Cache',
    difficulty: 'Medium',
    priority: 2,
    summary: 'Mental model of autoregressive transformer inference: attention, next-token prediction, prefill vs decode, KV cache.',
    intuition: 'An LLM predicts one next token at a time from a probability distribution over the vocabulary. Self-attention lets each token weigh every earlier token: softmax(QK^T / sqrt(d)) V. The KV cache stores past keys/values so each new token does not recompute the whole prompt.',
    pitfalls: 'Believing the model "looks things up" or "knows" facts reliably; treating outputs as deterministic; ignoring that attention cost grows with context length.',
    notes: '### Key ideas for interviews\n- Autoregressive: output token is appended to input, repeat until stop token.\n- Attention is O(n^2) in sequence length (before optimisations like FlashAttention).\n- KV cache trades GPU memory for speed; it is why long contexts and many concurrent users are memory-bound.\n- Decode is memory-bandwidth-bound; prefill is compute-bound.\n- Hallucination is a consequence of next-token likelihood without grounding, so grounding (RAG, tools) is the fix, not "better prompts" alone.\n- Training stages: pre-training -> supervised fine-tuning -> preference tuning (RLHF/DPO) -> optional reasoning RL.',
  },
  {
    category: C1,
    title: 'Sampling: Temperature, Top-p, Top-k & Stop Sequences',
    difficulty: 'Easy',
    priority: 2,
    summary: 'Controlling randomness and termination of generation, and when to use which setting.',
    intuition: 'Temperature rescales logits before softmax: low = peaked/predictable, high = diverse. Top-p (nucleus) keeps the smallest set of tokens whose cumulative probability reaches p; top-k keeps the k most likely. Use low temperature for extraction, classification and tool calls; higher for brainstorming.',
    pitfalls: 'Expecting temperature 0 to be fully deterministic (batching and floating-point make it only mostly stable); tuning temperature and top-p together aggressively; some reasoning models ignore or fix these parameters.',
    notes: '### Practical defaults\n- Extraction / JSON / tool calling: temperature 0 to 0.2\n- Chat / summarisation: 0.3 to 0.7\n- Creative: 0.8+\n- Stop sequences end generation early and save tokens.\n- Seed parameters (where supported) improve reproducibility but are not a guarantee.\n- Always pin the model version in production so behaviour does not shift under you.',
  },
  {
    category: C1,
    title: 'Model Selection: Frontier vs Small vs Open-Weight',
    difficulty: 'Medium',
    priority: 2,
    summary: 'Choosing models by quality, latency, cost, context size, modality, privacy and licensing.',
    intuition: 'Use the cheapest model that passes your evals. Route easy/high-volume steps (classification, extraction, routing) to small fast models and reserve frontier or reasoning models for hard planning and synthesis.',
    pitfalls: 'Picking by leaderboard instead of your own eval set; hard-coding a single vendor; ignoring data residency and retention policy.',
    notes: '### Decision matrix\n- Quality-critical reasoning/coding: frontier or reasoning models.\n- High-volume, simple: small models (cost and latency 10x lower).\n- Privacy / on-prem / offline: open-weight models (Llama, Qwen, Mistral families) via Ollama, vLLM.\n- Multimodal: check vision/audio support and image token costs.\n- Always abstract the provider (IChatClient in .NET, AI SDK providers in TS) so swapping is a config change.\n- Re-run evals on every model upgrade.',
  },
  {
    category: C1,
    title: 'Structured Outputs & JSON Schema',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Forcing model output into a validated schema so backend code can consume it safely.',
    intuition: 'Free text is for humans; programs need typed data. Use provider structured-output / JSON-schema modes (constrained decoding) and still validate on your side with Zod or System.Text.Json, because a valid shape does not mean valid meaning.',
    pitfalls: 'Parsing JSON out of prose with regex; trusting enum values without validation; deeply nested schemas that hurt accuracy; no retry-with-error-feedback path.',
    notes: '### Pattern\n1. Define schema (Zod / C# record).\n2. Ask provider for structured output with that schema.\n3. Validate; on failure, send the validation error back once or twice, then fail.\n4. Add business validation (ranges, IDs exist in DB).\n\nKeep schemas flat, use descriptions on fields (the model reads them), prefer enums over free strings.',
    code: "import { z } from 'zod';\nimport { generateObject } from 'ai';\nimport { openai } from '@ai-sdk/openai';\n\nconst Ticket = z.object({\n  category: z.enum(['billing', 'bug', 'feature']),\n  urgency: z.number().int().min(1).max(5),\n  summary: z.string().describe('One sentence'),\n});\n\nconst { object } = await generateObject({\n  model: openai('gpt-4o-mini'),\n  schema: Ticket,\n  prompt: 'Classify: ' + userMessage,\n});",
  },
  {
    category: C1,
    title: 'Embeddings & Semantic Similarity',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Turning text into vectors so meaning can be compared with cosine similarity; the foundation of RAG, search and memory.',
    intuition: 'An embedding model maps text to a fixed-length vector where similar meaning means small angle. Cosine similarity = dot(a,b)/(|a||b|); with normalised vectors it equals the dot product.',
    pitfalls: 'Mixing embedding models between indexing and querying; not re-indexing after changing models; embedding huge chunks (diluted meaning); assuming semantic search handles exact IDs or rare keywords well.',
    notes: '### Facts to remember\n- Dimensions (e.g. 384, 768, 1536, 3072) affect storage and speed; some models support truncation (Matryoshka).\n- Store model name + version with every vector.\n- Query and document may need different prefixes/instructions for some models.\n- Embeddings are not secret: they can leak information about source text, so apply the same access control as the source.\n- Use for: semantic search, dedup, clustering, classification, routing, memory retrieval.',
    code: 'export const cosine = (a: number[], b: number[]) => {\n  let dot = 0, na = 0, nb = 0;\n  for (let i = 0; i < a.length; i++) { dot += a[i] * b[i]; na += a[i] ** 2; nb += b[i] ** 2; }\n  return dot / (Math.sqrt(na) * Math.sqrt(nb));\n};',
  },

  // ---------------- 2. Prompt & Context Engineering ----------------
  {
    category: C2,
    title: 'System Prompts, Roles & Instruction Hierarchy',
    difficulty: 'Easy',
    priority: 1,
    summary: 'Structuring system, developer and user messages so behaviour is stable and instructions are prioritised correctly.',
    intuition: 'The system prompt defines role, rules, tools policy and output format; user content is untrusted data. Be explicit, specific and positive ("do X") and give the model an out ("if unsure say so").',
    pitfalls: 'Putting secrets in the system prompt (it can leak); contradictory rules; giant prompts with no structure; mixing instructions with untrusted retrieved text.',
    notes: '### Prompt skeleton\n1. Role & goal\n2. Context / domain facts\n3. Rules & constraints\n4. Tool-use guidance\n5. Output format (schema or template)\n6. Examples\n\nUse XML-style or markdown delimiters to separate sections and untrusted data (<document>...</document>). Keep prompts in files with version control, not scattered in code.',
  },
  {
    category: C2,
    title: 'Few-Shot, Chain-of-Thought & Reasoning Models',
    difficulty: 'Medium',
    priority: 2,
    summary: 'Techniques that improve accuracy: examples, step-by-step reasoning, and when dedicated reasoning models make them unnecessary.',
    intuition: 'Few-shot examples teach format and edge cases better than prose. Chain-of-thought gives the model room to compute intermediate steps. Reasoning models do this internally, so over-prescribing steps can hurt.',
    pitfalls: 'Examples that are all similar (model copies them); leaking test cases into prompts; paying for long reasoning on trivial tasks; relying on displayed reasoning as a faithful explanation.',
    notes: '### Guidance\n- 3 to 5 diverse, realistic examples covering edge cases and a refusal/unknown case.\n- For standard models: "think step by step" on multi-step logic.\n- For reasoning models: state the goal and constraints, let them think; control cost via reasoning-effort settings.\n- Self-consistency: sample N answers and take the majority for high-stakes classification.\n- Always measure with an eval set, not by feel.',
  },
  {
    category: C2,
    title: 'Context Engineering for Agents',
    difficulty: 'Hard',
    priority: 1,
    summary: 'Curating exactly what goes into the context window each step: instructions, tools, retrieved data, history, memory.',
    intuition: 'Context is a scarce resource with diminishing returns. Give the smallest set of high-signal tokens that makes the next step succeed: just-in-time retrieval, compaction of old history, structured notes outside the window, and sub-agents with clean contexts.',
    pitfalls: 'Dumping all tools and documents in every call; letting tool outputs grow unbounded; stale or contradictory facts left in history; poisoning the context with a failed attempt and never pruning it.',
    notes: '### Techniques\n- Compaction: summarise old turns, keep decisions and open TODOs.\n- Note-taking: agent writes progress to a file/DB and reads it back (survives context resets).\n- Just-in-time retrieval: hold identifiers (paths, URLs, IDs) and load content only when needed.\n- Tool-result clearing: drop old raw outputs once consumed.\n- Sub-agents: delegate a search/analysis task and return only a condensed result.\n- Order matters: static content first (enables prompt caching), volatile content last.',
    url: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents',
  },
  {
    category: C2,
    title: 'Prompt Templates, Versioning & Regression Testing',
    difficulty: 'Medium',
    priority: 2,
    summary: 'Treating prompts as code: templates, versions, review, and automated regression checks against an eval set.',
    intuition: 'A prompt change is a behaviour change. Store prompts in source control with an ID/version, log the version on every request, and run the eval suite in CI before shipping.',
    pitfalls: 'Editing prompts directly in production dashboards with no history; no way to correlate a bad answer to a prompt version; fixing one failure and silently breaking five others.',
    notes: '### Workflow\n1. Prompt file with variables ({{customer_name}}).\n2. Unit evals: representative inputs + assertions (schema valid, contains/forbids phrases, judge score).\n3. CI gate: score must not regress beyond threshold.\n4. Canary/A-B new prompt on a slice of traffic.\n5. Log prompt_version, model, tokens, latency per request.',
  },

  // ---------------- 3. RAG & Vector Search ----------------
  {
    category: C3,
    title: 'RAG Architecture: Ingestion to Generation',
    difficulty: 'Medium',
    priority: 1,
    summary: 'End-to-end Retrieval-Augmented Generation pipeline: load, chunk, embed, index, retrieve, rerank, generate, cite.',
    intuition: 'RAG grounds the model in your data at query time instead of baking knowledge into weights. Quality is mostly determined by retrieval: if the right chunk is not retrieved, no prompt can save the answer.',
    pitfalls: 'Evaluating only the final answer (cannot tell retrieval vs generation failure); no citations; ignoring document permissions; stale index with no refresh pipeline.',
    notes: '### Pipeline\n- Ingestion: parse (PDF/HTML/MD), clean, chunk, embed, upsert with metadata (source, ACL, version, updated_at).\n- Query: rewrite -> embed -> retrieve top-k -> (hybrid + rerank) -> assemble context -> generate with citations.\n- Enforce access control at retrieval (metadata filter by user/tenant), never after generation.\n- Instruct: "Answer only from the context; if missing say you do not know."\n- Keep an incremental re-index job keyed by content hash.',
  },
  {
    category: C3,
    title: 'Chunking Strategies & Metadata',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Splitting documents into retrievable units that preserve meaning, with metadata for filtering and citation.',
    intuition: 'Chunks should be self-contained answers. Structure-aware splitting (by heading/section/function) beats fixed-size splitting; small chunks retrieve precisely, large chunks give context, so parent-child retrieval gives both.',
    pitfalls: 'Cutting tables/code mid-way; no overlap at boundaries; losing the heading context (prepend the title path to each chunk); one chunk size for all document types.',
    notes: '### Starting points\n- 200 to 800 tokens, 10 to 20% overlap for prose.\n- Split on headings first, then paragraphs, then sentences.\n- Code: chunk by function/class; keep file path and language in metadata.\n- Contextual retrieval: prepend a short LLM-generated situating sentence to each chunk before embedding.\n- Metadata: source URL, title path, page, tenant_id, ACL, doc_version, created/updated.',
  },
  {
    category: C3,
    title: 'Vector Databases, ANN Indexes & pgvector',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Approximate nearest neighbour search (HNSW, IVF), distance metrics, and choosing between pgvector and dedicated vector stores.',
    intuition: 'Exact search is O(n); ANN indexes trade a little recall for big speed. HNSW is a layered proximity graph (tune m, ef_construction, ef_search). IVF clusters vectors and probes a few lists. For most apps already on Postgres, pgvector is enough.',
    pitfalls: 'Building an index before loading data (IVFFlat needs data for clustering); not applying metadata filters efficiently (post-filtering kills recall); ignoring memory footprint of HNSW.',
    notes: '### pgvector operators\n- <-> L2 distance, <=> cosine distance, <#> negative inner product.\n- Index: CREATE INDEX ON docs USING hnsw (embedding vector_cosine_ops);\n- Tune at query time: SET hnsw.ef_search = 100;\n\n### Choosing\n- pgvector: transactional joins, one system, up to millions of vectors.\n- Dedicated (Pinecone, Qdrant, Weaviate, Milvus, Azure AI Search): very large scale, built-in hybrid, managed ops.',
    code: "CREATE EXTENSION IF NOT EXISTS vector;\nCREATE TABLE chunks (\n  id bigserial PRIMARY KEY,\n  doc_id text, tenant_id text, content text,\n  embedding vector(1536)\n);\nCREATE INDEX ON chunks USING hnsw (embedding vector_cosine_ops);\n\nSELECT id, content, 1 - (embedding <=> $1) AS score\nFROM chunks WHERE tenant_id = $2\nORDER BY embedding <=> $1 LIMIT 8;",
  },
  {
    category: C3,
    title: 'Hybrid Search, RRF & Reranking',
    difficulty: 'Hard',
    priority: 1,
    summary: 'Combining keyword (BM25) and vector search, fusing ranks, and re-scoring with a cross-encoder reranker.',
    intuition: 'Vectors capture meaning but miss exact tokens (error codes, SKUs); BM25 does the opposite. Reciprocal Rank Fusion merges both lists: score = sum of 1/(k + rank), typically k = 60. A cross-encoder reranker then re-scores the top 50 to 100 candidates down to the best 5 to 10.',
    pitfalls: 'Adding a reranker without measuring recall@k first; sending too many chunks to the LLM; ignoring latency of the rerank step.',
    notes: '### Metrics\n- Retrieval: recall@k, precision@k, MRR, nDCG.\n- Build a labelled set of (question -> relevant chunk ids) from real queries.\n\n### Pipeline\nBM25 top 50 + vector top 50 -> RRF -> reranker top 8 -> LLM.',
    code: 'export function rrf(lists: string[][], k = 60) {\n  const score = new Map<string, number>();\n  for (const list of lists)\n    list.forEach((id, rank) => score.set(id, (score.get(id) ?? 0) + 1 / (k + rank + 1)));\n  return [...score.entries()].sort((a, b) => b[1] - a[1]).map(([id]) => id);\n}',
  },
  {
    category: C3,
    title: 'Advanced RAG: Query Rewriting, HyDE, Agentic RAG & GraphRAG',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Techniques beyond naive RAG for ambiguous, multi-hop and global questions.',
    intuition: 'Rewrite the user question into good search queries (decompose, expand, use chat history). HyDE embeds a hypothetical answer. Agentic RAG lets the model decide when and what to retrieve, iterating until it has enough. GraphRAG builds an entity graph for corpus-wide questions.',
    pitfalls: 'Multiplying LLM calls (latency/cost) for questions that simple retrieval handles; letting the agent loop without a step budget; building a graph when the corpus does not need it.',
    notes: '### When to use\n- Follow-up questions: condense with history.\n- Multi-hop ("compare A and B"): decompose into sub-queries, retrieve each, synthesise.\n- Low retrieval confidence: fallback query rewrite, then admit uncertainty.\n- Global/summary questions: hierarchical summaries or GraphRAG.\n- Expose retrieval as a tool (search_docs) so the agent can call it multiple times.',
  },
  {
    category: C3,
    title: 'Evaluating RAG: Faithfulness, Relevance & Retrieval Quality',
    difficulty: 'Hard',
    priority: 1,
    summary: 'Measuring retrieval and generation separately so failures can be diagnosed and fixed.',
    intuition: 'Split the problem: did we retrieve the right context (context recall/precision) and did the answer stay grounded in it (faithfulness) and address the question (answer relevance)?',
    pitfalls: 'Using only an LLM judge with no human calibration; test sets written by the same model that builds the system; no tracking over time.',
    notes: '### Metrics\n- Retrieval: recall@k, MRR, nDCG, context precision/recall.\n- Generation: faithfulness/groundedness, answer relevance, citation correctness, refusal correctness when no answer exists.\n- Tools: Ragas, DeepEval, Promptfoo, LangSmith/Langfuse datasets.\n- Build the golden set from real user questions plus synthetic ones; include unanswerable and adversarial cases.',
  },

  // ---------------- 4. Agent Fundamentals ----------------
  {
    category: C4,
    title: 'Workflows vs Agents: Choosing the Right Pattern',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Predefined LLM workflows (chaining, routing, parallelisation, orchestrator-workers, evaluator-optimizer) versus autonomous agents.',
    intuition: 'Workflows orchestrate LLMs through code paths you define; agents let the LLM direct its own process and tool use. Start with the simplest thing (a single call with retrieval), add workflow structure for reliability, and use a true agent only when the path cannot be predicted.',
    pitfalls: 'Reaching for an autonomous agent for a fixed process; no stop conditions; framework abstractions that hide prompts and make debugging impossible.',
    notes: '### Five workflow patterns\n1. Prompt chaining: fixed sequence with gates between steps.\n2. Routing: classify input then dispatch to a specialised path or model.\n3. Parallelisation: sectioning independent subtasks, or voting for confidence.\n4. Orchestrator-workers: a lead model splits dynamic subtasks and merges results.\n5. Evaluator-optimizer: generate, critique, refine loop.\n\nAgents add: tool use in a loop, environment feedback, and a stopping condition (done, max steps, budget, human checkpoint).',
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
  },
  {
    category: C4,
    title: 'The Agent Loop & ReAct',
    difficulty: 'Medium',
    priority: 1,
    summary: 'The core think-act-observe loop that powers tool-using agents, with proper termination and budgets.',
    intuition: 'Loop: send messages + tool definitions -> model returns text or tool calls -> run tools -> append results -> repeat until the model returns a final answer or a limit is hit. ReAct is this pattern with explicit reasoning between actions.',
    pitfalls: 'No max-iterations or token/cost budget; infinite retry of a failing tool; swallowing tool errors instead of returning them to the model; unbounded context growth.',
    notes: '### Minimum viable agent\n- Tools described by JSON schema.\n- Loop with max_steps (e.g. 10 to 25), cost cap and timeout.\n- Tool errors returned as tool_result with is_error so the model can adapt.\n- Detect repeated identical calls (loop detection).\n- Persist every step for tracing and replay.',
    code: "async function runAgent(messages: Msg[], tools: Tool[], maxSteps = 15) {\n  for (let step = 0; step < maxSteps; step++) {\n    const res = await llm({ messages, tools });\n    messages.push(res.message);\n    if (!res.toolCalls?.length) return res.message.content; // final answer\n    for (const call of res.toolCalls) {\n      const result = await safeExecute(tools, call); // returns error text on failure\n      messages.push({ role: 'tool', toolCallId: call.id, content: result });\n    }\n  }\n  throw new Error('Agent exceeded max steps');\n}",
  },
  {
    category: C4,
    title: 'Tool / Function Calling Design',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Designing tool schemas, descriptions and results so models call them correctly and safely.',
    intuition: 'Tools are an API for the model. Clear names, precise descriptions with when-to-use guidance, strongly-typed parameters, and concise, informative results make the difference between a flaky and a reliable agent.',
    pitfalls: 'Too many overlapping tools; vague descriptions; returning huge raw payloads; tools with side effects that are not idempotent; trusting model-provided arguments without validation.',
    notes: '### Design rules\n- Few, well-scoped tools; merge near-duplicates.\n- Description says what, when, and when NOT to use.\n- Validate arguments server-side (schema + authorisation as the end user, not as the agent).\n- Return only what is needed, with stable IDs the model can pass to the next tool.\n- Make writes idempotent (idempotency key) and support dry-run/confirm for destructive ones.\n- Support parallel tool calls when calls are independent.',
    code: "const searchOrders = tool({\n  description: 'Search the current user\\'s orders by status or date range. Use for order lookups. Do NOT use for refunds.',\n  inputSchema: z.object({\n    status: z.enum(['open', 'shipped', 'cancelled']).optional(),\n    from: z.string().date().optional(),\n  }),\n  execute: async (args, { userId }) => db.orders.search(userId, args),\n});",
  },
  {
    category: C4,
    title: 'Planning, Reflection & Self-Correction',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Letting agents plan multi-step work, verify results, and recover from errors.',
    intuition: 'Explicit plans (a todo list the agent updates) keep long tasks on track. Reflection steps check output against requirements using real signals (tests, schema validation, search results) rather than the model re-reading its own answer.',
    pitfalls: 'Self-critique without external ground truth just rubber-stamps errors; over-planning for simple tasks; plans that never get updated.',
    notes: '### Patterns\n- Plan-and-execute: planner produces steps, executor runs them, replan on failure.\n- Verifier: run tests/linters/validators and feed failures back.\n- Reflexion: store lessons from failed attempts in memory for the next try.\n- Cap retries and escalate to a human when blocked.',
  },
  {
    category: C4,
    title: 'Agent Memory: Short-Term, Long-Term & Episodic',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Persisting useful state across steps and sessions without bloating the context window.',
    intuition: 'Short-term memory is the context window. Long-term memory is external: facts/preferences (semantic), past interactions (episodic), and learned procedures (procedural), retrieved when relevant.',
    pitfalls: 'Storing everything (noise); no expiry or correction of wrong memories; leaking one user\'s memory to another; treating retrieved memory as trusted instructions.',
    notes: '### Implementation\n- Summarise conversation incrementally; store summary + key facts.\n- Extract durable facts ("prefers TypeScript") with an LLM step, dedupe, store in DB/vector index keyed by user.\n- Retrieve top relevant memories per turn and place them in a clearly-labelled section.\n- Give users view/edit/delete controls; honour privacy rules.\n- Scope strictly by tenant and user.',
  },
  {
    category: C4,
    title: 'Multi-Agent Systems: Supervisor, Handoffs & Sub-Agents',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Splitting work across specialised agents and coordinating them.',
    intuition: 'Multiple agents help when subtasks are parallel, need different tools/permissions, or would overflow one context. They cost more tokens and add coordination failures, so use one agent until you have evidence it is not enough.',
    pitfalls: 'Agents talking in circles; vague hand-off contracts; duplicated work; no single owner of the final answer; debugging without traces.',
    notes: '### Topologies\n- Supervisor/orchestrator with worker agents.\n- Hand-off (swarm): agent transfers control with context to another.\n- Parallel researchers + synthesiser.\n- Critic/reviewer pair.\n\n### Rules\n- Each sub-agent gets a precise brief: objective, output format, tool guidance, boundaries.\n- Return condensed results to the lead, not full transcripts.\n- Trace every agent run under one parent trace ID.',
  },

  // ---------------- 5. Tools, MCP & Frameworks ----------------
  {
    category: C5,
    title: 'Model Context Protocol (MCP)',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Open protocol for connecting AI applications to tools, data and prompts through standard servers.',
    intuition: 'MCP is like USB-C for AI tools: build one server and any MCP-capable client (IDE, desktop assistant, your own agent) can use it. It uses JSON-RPC 2.0 over stdio (local) or Streamable HTTP (remote).',
    pitfalls: 'Installing untrusted MCP servers (they run code and feed content into the model); over-broad tool permissions; exposing hundreds of tools and flooding the context; skipping auth on remote servers.',
    notes: '### Concepts\n- Server primitives: tools (actions), resources (readable data), prompts (templates).\n- Client features: sampling, roots, elicitation.\n- Transports: stdio for local, Streamable HTTP for remote; remote servers should use OAuth-based authorisation.\n- SDKs: TypeScript, Python, C# (official), Java, Kotlin.\n- Treat tool descriptions and outputs as untrusted input (prompt-injection surface).',
    code: "import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';\nimport { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';\nimport { z } from 'zod';\n\nconst server = new McpServer({ name: 'topics', version: '1.0.0' });\nserver.tool('get_topic', { id: z.string() }, async ({ id }) => ({\n  content: [{ type: 'text', text: JSON.stringify(await repo.get(id)) }],\n}));\nawait server.connect(new StdioServerTransport());",
    url: 'https://modelcontextprotocol.io',
  },
  {
    category: C5,
    title: 'Agent-to-Agent (A2A) & Interoperability',
    difficulty: 'Hard',
    priority: 3,
    summary: 'Protocols for agents built on different stacks to discover each other and collaborate.',
    intuition: 'MCP connects an agent to tools and data; A2A connects agents to other agents. Agents publish an Agent Card describing skills and endpoints, then exchange tasks and messages over HTTP.',
    pitfalls: 'Assuming remote agents are trustworthy; ignoring authentication and task-level authorisation; chaining agents with no timeouts.',
    notes: '### Mental model\n- MCP = vertical (agent <-> tools).\n- A2A = horizontal (agent <-> agent).\n- Key objects: Agent Card (capabilities), Task (long-running unit with lifecycle), Message/Artifact.\n- Use when crossing team/vendor boundaries; inside one codebase plain function calls or in-process orchestration are simpler.',
  },
  {
    category: C5,
    title: 'LangGraph: Stateful Agent Graphs, Checkpoints & Human-in-the-Loop',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Modelling agents as graphs of nodes with shared state, persistence and interrupts.',
    intuition: 'A graph makes control flow explicit: nodes (LLM call, tool, function), edges (conditional routing), and a typed state. A checkpointer saves state after each step so runs can resume, be inspected, rewound, or paused for human approval.',
    pitfalls: 'Using a framework when a 30-line loop would do; hiding prompts behind abstractions; not persisting checkpoints in production (in-memory only).',
    notes: '### Why graphs\n- Deterministic structure around non-deterministic LLM steps.\n- Interrupts: pause before a sensitive tool call, wait for approval, then resume.\n- Time travel/debugging via checkpoints.\n- Streaming of intermediate state to the UI.\n\nAlternatives: OpenAI Agents SDK, Mastra, Vercel AI SDK agents, Microsoft Agent Framework. Learn one deeply, keep the concepts portable.',
  },
  {
    category: C5,
    title: '.NET AI Stack: Microsoft.Extensions.AI & Agent Framework',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Building LLM features in C#: IChatClient, IEmbeddingGenerator, function invocation, and agent orchestration for .NET backends.',
    intuition: 'Microsoft.Extensions.AI gives provider-agnostic abstractions (IChatClient, IEmbeddingGenerator) with middleware (function invocation, caching, logging, OpenTelemetry). Higher-level agent orchestration is provided by Microsoft Agent Framework (the evolution of Semantic Kernel and AutoGen ideas).',
    pitfalls: 'Binding business code to one vendor SDK; registering clients as singletons without considering options per request; forgetting cancellation tokens on streaming calls.',
    notes: '### Key pieces\n- IChatClient: GetResponseAsync / GetStreamingResponseAsync.\n- ChatClientBuilder pipeline: UseFunctionInvocation(), UseOpenTelemetry(), UseDistributedCache(), UseLogging().\n- AIFunctionFactory.Create(method) turns a C# method into a tool.\n- DI registration: services.AddChatClient(...).\n- Use Azure OpenAI / OpenAI / Ollama / GitHub Models interchangeably behind the interface.\n- Pair with pgvector or Azure AI Search for RAG, and Semantic Kernel/Agent Framework for multi-step agents.',
    code: 'IChatClient client = new ChatClientBuilder(\n        new OpenAIClient(apiKey).GetChatClient("gpt-4o-mini").AsIChatClient())\n    .UseFunctionInvocation()\n    .UseOpenTelemetry()\n    .Build();\n\nvar options = new ChatOptions { Tools = [AIFunctionFactory.Create(GetOrderStatus)] };\nawait foreach (var update in client.GetStreamingResponseAsync(messages, options, ct))\n    Console.Write(update.Text);',
  },
  {
    category: C5,
    title: 'Vercel AI SDK & TypeScript Agent SDKs',
    difficulty: 'Medium',
    priority: 1,
    summary: 'TypeScript toolkit for streaming chat, tool calling, structured output and agents in Next.js apps.',
    intuition: 'The AI SDK normalises providers behind generateText/streamText/generateObject, with a useChat hook on the client and typed tools on the server. Same concepts exist in OpenAI Agents SDK, Mastra and LangChain.js.',
    pitfalls: 'Calling provider keys from the browser; not setting maxDuration on serverless routes; not handling abort/disconnect; coupling UI message format to one provider.',
    notes: '### Server route sketch\n- streamText({ model, system, messages, tools, stopWhen }) returns a stream.\n- Return result.toUIMessageStreamResponse() to the client.\n- Client uses useChat to render parts (text, tool calls, reasoning).\n- Multi-step tool loops are controlled by stop conditions (step count).\n- Keep API keys server-side only; add auth and rate limits on the route.',
    code: "import { streamText, convertToModelMessages, stepCountIs } from 'ai';\nimport { openai } from '@ai-sdk/openai';\n\nexport async function POST(req: Request) {\n  const { messages } = await req.json();\n  const result = streamText({\n    model: openai('gpt-4o'),\n    system: 'You are a helpful assistant.',\n    messages: convertToModelMessages(messages),\n    tools: { searchOrders },\n    stopWhen: stepCountIs(8),\n  });\n  return result.toUIMessageStreamResponse();\n}",
  },

  // ---------------- 6. Full-Stack AI Apps ----------------
  {
    category: C6,
    title: 'Streaming Responses: SSE, Backpressure & Cancellation',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Delivering tokens to the browser as they are generated, and handling disconnects and proxies correctly.',
    intuition: 'Time-to-first-token is what users feel. Server-Sent Events (text/event-stream) are the simplest one-way streaming transport; propagate client aborts to the model call so you stop paying for tokens nobody reads.',
    pitfalls: 'Reverse proxies buffering the stream (disable buffering, e.g. nginx proxy_buffering off); no heartbeat; ignoring request abort signals; swallowing mid-stream errors.',
    notes: '### Checklist\n- Headers: Content-Type text/event-stream, Cache-Control no-cache, Connection keep-alive.\n- Forward AbortSignal to the LLM client.\n- Emit structured events (text-delta, tool-call, error, done).\n- Retry/resume: include event ids so clients can reconnect.\n- ASP.NET Core: return IAsyncEnumerable<T> from a minimal API or use TypedResults.ServerSentEvents.\n- WebSockets only if you need bidirectional realtime (voice, collaborative).',
    code: 'app.MapPost("/chat", (ChatRequest req, IChatClient chat, CancellationToken ct) =>\n    TypedResults.ServerSentEvents(Stream(req, chat, ct)));\n\nstatic async IAsyncEnumerable<string> Stream(ChatRequest req, IChatClient chat,\n    [EnumeratorCancellation] CancellationToken ct)\n{\n    await foreach (var u in chat.GetStreamingResponseAsync(req.Messages, cancellationToken: ct))\n        yield return u.Text;\n}',
  },
  {
    category: C6,
    title: 'Building the Chat UI: useChat, Tool Rendering & Generative UI',
    difficulty: 'Medium',
    priority: 2,
    summary: 'Frontend patterns for AI products: streaming messages, tool-call states, optimistic UI, citations, stop/regenerate.',
    intuition: 'Treat a message as a list of typed parts (text, reasoning, tool call, source). Render each part with its own component, show tool progress, and let the model choose a UI component by calling a tool that maps to a React component.',
    pitfalls: 'Re-rendering the whole transcript on every token; rendering model-produced HTML unsanitised (XSS); no stop button; losing history on refresh.',
    notes: '### UX essentials\n- Stop, retry, edit-and-resubmit, copy.\n- Show sources/citations with links back to the document chunk.\n- Show agent steps ("Searching orders...") for transparency.\n- Markdown render with a sanitiser; syntax highlighting for code.\n- Persist conversations server-side; paginate long histories.\n- Human approval cards for sensitive tool calls.\n- Accessibility: aria-live for streamed text, keyboard shortcuts.',
  },
  {
    category: C6,
    title: 'LLM Backends in .NET / Node: API Design, Auth & Multi-Tenancy',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Structuring a production API around LLM calls: auth, tenant isolation, per-user context, request limits and error mapping.',
    intuition: 'The LLM is just another unreliable downstream dependency. Wrap it behind a service interface, run tools with the end user\'s identity, and isolate tenants at the data layer (never rely on the prompt to enforce isolation).',
    pitfalls: 'Running tools with a powerful service account; passing user identity only in the prompt; no timeouts; leaking provider error messages to clients.',
    notes: '### Layers\n1. Controller / minimal API: auth (JWT), validation, rate limit.\n2. Application service: builds messages, selects model, applies budgets.\n3. Tool layer: authorises every call against the current user.\n4. Provider layer: IChatClient with Polly resilience, retries with jitter, circuit breaker.\n5. Persistence: conversations, messages, usage records, feedback.\n\nMap provider errors (429, 5xx, content filter) to clean API responses and fallbacks.',
  },
  {
    category: C6,
    title: 'Long-Running Agent Jobs: Queues, Durable Execution & Resumability',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Running multi-minute agent tasks reliably outside the request/response cycle.',
    intuition: 'Serverless request timeouts and flaky networks kill long agent runs. Enqueue the job, run it in a worker with checkpointing after every step, and stream progress to the UI via SSE or polling.',
    pitfalls: 'Non-idempotent tools re-executed on retry; losing state when a worker restarts; no cancellation; unbounded cost per job.',
    notes: '### Building blocks\n- Queue + worker: BackgroundService with System.Threading.Channels, Hangfire, Azure Service Bus; or Inngest, Temporal, Azure Durable Functions in TS/.NET.\n- Persist run state (steps, tool results) so a retry replays instead of redoing side effects.\n- Job API: POST /runs -> 202 + runId; GET /runs/{id}; SSE /runs/{id}/events; DELETE to cancel.\n- Per-run budgets: max steps, tokens, wall-clock.',
  },
  {
    category: C6,
    title: 'Cost & Latency Control: Caching, Routing, Rate Limits & Budgets',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Keeping AI features fast and affordable at scale.',
    intuition: 'Biggest wins in order: shorter prompts, prompt caching (stable prefix first), model routing, response/semantic caching, then batch APIs for offline work. Enforce per-user and per-tenant token budgets to prevent runaway bills.',
    pitfalls: 'Semantic cache returning another user\'s answer; caching responses that depend on private data; no per-user quota; ignoring output-length limits.',
    notes: '### Toolbox\n- Provider prompt caching: place system prompt and static docs at the start; vary the end.\n- Exact-match cache for deterministic requests (hash of prompt+params).\n- Semantic cache with a high similarity threshold and tenant scoping.\n- Router: small model first, escalate on low confidence.\n- Batch APIs (typically ~50% cheaper) for evals, backfills, enrichment.\n- Rate limiting: token-bucket per user/tenant (ASP.NET Core RateLimiter) measured in tokens, not only requests.\n- Dashboards: cost per user, per feature, per model.',
  },

  // ---------------- 7. Evals & Observability ----------------
  {
    category: C7,
    title: 'Building Eval Datasets & LLM-as-Judge',
    difficulty: 'Hard',
    priority: 1,
    summary: 'Creating repeatable evaluations for non-deterministic systems, using code graders, LLM judges and human review.',
    intuition: 'You cannot improve what you cannot measure. Start with 50 to 200 real examples, write the cheapest reliable grader for each (exact match, schema, regex, unit test), and use an LLM judge with a rubric only where needed, calibrated against human labels.',
    pitfalls: 'Judge biases (position, verbosity, self-preference); vague rubrics; overfitting prompts to the eval set; never refreshing the set with production failures.',
    notes: '### Process\n1. Collect cases from logs, support tickets and edge cases.\n2. Define success criteria per case.\n3. Graders: deterministic first, then rubric-based LLM judge (pairwise comparison reduces bias; randomise order).\n4. Track score per category, not just overall.\n5. Run in CI; keep a held-out set.\n6. Add every production bug as a new case.\n\nTools: Promptfoo, Braintrust, LangSmith, Langfuse, DeepEval, Inspect.',
  },
  {
    category: C7,
    title: 'Tracing & Observability with OpenTelemetry GenAI',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Seeing inside prompts, tool calls, tokens, latency and cost for every request.',
    intuition: 'Agents are debugged by reading traces. Capture one trace per user request with spans for each LLM call and tool call, including model, prompt version, token counts, latency, and errors. OpenTelemetry GenAI semantic conventions standardise attribute names (gen_ai.*).',
    pitfalls: 'Logging raw prompts containing PII without redaction; no correlation between traces and user feedback; sampling away the failing runs.',
    notes: '### What to record\n- gen_ai.request.model, gen_ai.usage.input_tokens / output_tokens, finish reason.\n- Prompt version, tool names + arguments + latency + status.\n- User feedback (thumbs) linked to trace id.\n- Cost per trace computed from token usage.\n\nBackends: Langfuse, LangSmith, Arize Phoenix, Azure Monitor/Application Insights, Grafana/Tempo. In .NET: ChatClientBuilder.UseOpenTelemetry().',
  },
  {
    category: C7,
    title: 'Evaluating Agents: Trajectories, Tool Accuracy & Reliability',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Metrics for multi-step agents beyond final-answer quality.',
    intuition: 'Agents can reach the right answer the wrong way (or fail only occasionally). Measure task success in a sandboxed environment, check tool-call correctness and arguments, count steps/cost, and run each case multiple times (pass^k) to measure consistency.',
    pitfalls: 'Testing against live production systems with side effects; single-run results on non-deterministic agents; ignoring cost and step count regressions.',
    notes: '### Metrics\n- Task success rate (end-state check, e.g. DB row exists).\n- Tool selection and argument accuracy.\n- Steps, tokens, latency, cost per task.\n- Recovery from injected tool failures.\n- Safety: refusal of disallowed actions, injection resistance.\n- pass@k (any of k succeed) vs pass^k (all k succeed) for reliability.',
  },
  {
    category: C7,
    title: 'Guardrails, Monitoring & Feedback Loops',
    difficulty: 'Medium',
    priority: 2,
    summary: 'Input/output validation layers and production monitoring that turns real usage into improvements.',
    intuition: 'Defence in depth: validate inputs (length, language, injection heuristics), constrain outputs (schema, allow-lists, moderation), and monitor in production (error rate, refusal rate, cost, latency, thumbs-down) with alerts.',
    pitfalls: 'Relying on an LLM guardrail as the only control; guardrails that block legitimate users with no appeal path; no sampling of production conversations for review.',
    notes: '### Layers\n- Pre-model: size limits, PII detection, topic filters, rate limits.\n- Model: system policy, structured output.\n- Post-model: schema validation, content moderation, citation check, regex for secrets.\n- Action: policy engine for tool calls (allow-list, spend limits, approval).\n- Feedback: thumbs, corrections, escalations -> labelled dataset -> eval set.',
  },

  // ---------------- 8. Safety & Security ----------------
  {
    category: C8,
    title: 'OWASP Top 10 for LLM Applications',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Know the standard threat list for LLM systems and the main mitigation for each.',
    intuition: 'LLM01 Prompt Injection, LLM02 Sensitive Information Disclosure, LLM03 Supply Chain, LLM04 Data and Model Poisoning, LLM05 Improper Output Handling, LLM06 Excessive Agency, LLM07 System Prompt Leakage, LLM08 Vector and Embedding Weaknesses, LLM09 Misinformation, LLM10 Unbounded Consumption (2025 list).',
    pitfalls: 'Treating model output as trusted (XSS, SQL injection, command injection through generated content); giving agents broad permissions; unlimited token usage enabling denial-of-wallet.',
    notes: '### Mitigation cheat sheet\n- Injection: separate instructions from data, least privilege, human approval for risky actions.\n- Output handling: encode/sanitise output, parameterise SQL, never eval or exec model text.\n- Excessive agency: minimal tool set, scoped credentials, confirm destructive actions.\n- Vector weaknesses: ACLs on retrieval, validate ingested documents.\n- Unbounded consumption: max_tokens, per-user quotas, timeouts, loop limits.\n- Supply chain: pin/verify models, MCP servers and packages.',
    url: 'https://genai.owasp.org/llm-top-10/',
  },
  {
    category: C8,
    title: 'Prompt Injection & the Lethal Trifecta',
    difficulty: 'Hard',
    priority: 1,
    summary: 'How direct and indirect prompt injection works against agents, and architectural defences that actually hold.',
    intuition: 'Models cannot reliably distinguish instructions from data. An agent is at serious risk when it combines (1) access to private data, (2) exposure to untrusted content, and (3) the ability to communicate externally. Remove at least one leg of that trifecta.',
    pitfalls: '"Ignore malicious instructions" prompts as the only defence; letting a browsing/email-reading agent also send email or make HTTP requests with private data; rendering markdown images from model output (data exfiltration via URLs).',
    notes: '### Defences\n- Least privilege and per-task scoped credentials.\n- Separate agents: one reads untrusted content with no powerful tools, another acts on a sanitised, structured summary.\n- Human approval for actions with side effects or external communication.\n- Egress allow-lists; strip/deny auto-loaded remote images and links from output.\n- Treat all retrieved text, tool results and MCP descriptions as untrusted.\n- Red-team with known injection corpora in your evals.',
  },
  {
    category: C8,
    title: 'Tool Permissions, Sandboxing & Human-in-the-Loop',
    difficulty: 'Hard',
    priority: 1,
    summary: 'Containing what an agent can do: scopes, sandboxes, approval gates, audit logs.',
    intuition: 'Assume the agent will eventually be tricked or wrong. Limit blast radius: run code in isolated containers with no secrets and restricted network, grant tools the user\'s permissions only, and require approval for irreversible actions.',
    pitfalls: 'Shared long-lived API keys inside the agent environment; auto-approving all tool calls; no audit trail; approvals that show the model\'s description instead of the real action and arguments.',
    notes: '### Controls\n- Risk tiers: read-only (auto), reversible write (log), irreversible/financial/external (approve).\n- Approval UI shows exact arguments and a diff.\n- Sandboxes: containers/microVMs (e.g. Docker, gVisor, Firecracker), ephemeral FS, network egress policy.\n- Short-lived scoped tokens (OAuth on-behalf-of).\n- Immutable audit log: who/what/when/inputs/outputs.\n- Kill switch and per-run budgets.',
  },
  {
    category: C8,
    title: 'Privacy, PII Handling & Compliance for AI Features',
    difficulty: 'Medium',
    priority: 2,
    summary: 'Handling personal and confidential data when sending content to model providers and storing conversations.',
    intuition: 'Know where data goes: provider retention and training policies, region, sub-processors. Minimise what you send, redact where possible, and apply the same access controls to embeddings and chat logs as to the source data.',
    pitfalls: 'Logging full prompts forever; using consumer-tier APIs for business data; forgetting deletion requests must also remove vectors, caches and traces.',
    notes: '### Practices\n- Use enterprise endpoints with zero-retention / no-training terms (Azure OpenAI, Bedrock, Vertex, vendor enterprise plans).\n- PII redaction before logging (and optionally before the call).\n- Data classification decides which model/region is allowed.\n- Retention periods and deletion pipeline covering DB, vector index, caches, traces.\n- Be aware of regulation: GDPR/DPDP, SOC 2, HIPAA, EU AI Act risk categories.\n- Disclose AI use to users and provide feedback/appeal channels.',
  },

  // ---------------- 9. LLMOps & Production ----------------
  {
    category: C9,
    title: 'Reliability: Retries, Fallbacks, Model Routing & LLM Gateways',
    difficulty: 'Medium',
    priority: 1,
    summary: 'Keeping AI features available when providers rate-limit, time out or degrade.',
    intuition: 'Provider outages and 429s are normal. Use timeouts, exponential backoff with jitter, circuit breakers, and a fallback model/provider. A gateway centralises keys, routing, budgets, caching and logging.',
    pitfalls: 'Retrying non-idempotent tool executions; fallback model with different behaviour that breaks parsers; retry storms without jitter; no per-provider rate-limit awareness.',
    notes: '### Gateway features\n- Unified API across providers; key management.\n- Routing by cost/latency/health; automatic fallback.\n- Budgets and rate limits per team/user.\n- Caching, logging, redaction.\n- Options: LiteLLM, Portkey, Azure API Management AI gateway, Cloudflare AI Gateway, OpenRouter.\n- In .NET add Microsoft.Extensions.Http.Resilience (Polly v8) to the HttpClient used by the LLM client.',
  },
  {
    category: C9,
    title: 'Prompting vs RAG vs Fine-Tuning (LoRA, Distillation)',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Deciding which lever to pull to improve an AI feature.',
    intuition: 'Try in order: better prompt and examples, then retrieval/tools for missing knowledge, then fine-tuning for style, format, latency or cost. Fine-tuning teaches behaviour, not fresh facts. LoRA trains small adapter matrices instead of all weights.',
    pitfalls: 'Fine-tuning to inject changing knowledge; tiny low-quality datasets; no baseline to compare against; forgetting to re-evaluate after base model upgrades.',
    notes: '### Decision guide\n- Missing/changing facts -> RAG or tools.\n- Wrong tone/format/consistency -> few-shot, then fine-tune.\n- Too slow/expensive -> distil a large model\'s outputs into a small fine-tuned model.\n- Domain-specific classification at scale -> fine-tune small model.\n- Need hundreds to thousands of high-quality examples; hold out an eval set.\n- Preference tuning (DPO) for style/safety alignment.',
  },
  {
    category: C9,
    title: 'Local & Open-Weight Models: Ollama, vLLM & Quantization',
    difficulty: 'Medium',
    priority: 3,
    summary: 'Running models yourself for privacy, cost control, offline use and experimentation.',
    intuition: 'Ollama and llama.cpp make local dev trivial; vLLM serves open models at scale with continuous batching and PagedAttention. Quantization (8-bit, 4-bit) shrinks memory with small quality loss.',
    pitfalls: 'Assuming local equals free (GPU cost, ops); comparing a quantized small model to a frontier model on hard tasks; exposing an unauthenticated inference port.',
    notes: '### Quick start\n- ollama run llama3.1 ; the OpenAI-compatible endpoint is http://localhost:11434/v1.\n- Use the same IChatClient / AI SDK interface so dev uses local and prod uses hosted.\n- Memory rule of thumb: parameters x bytes-per-weight (4-bit ~ 0.5 bytes) plus KV cache.\n- Good for: embeddings, classification, privacy-sensitive prototypes, CI tests.',
    code: "import { createOpenAI } from '@ai-sdk/openai';\nconst local = createOpenAI({ baseURL: 'http://localhost:11434/v1', apiKey: 'ollama' });\nconst model = local('llama3.1');",
  },
  {
    category: C9,
    title: 'Latency Optimisation & Deploying AI Services',
    difficulty: 'Medium',
    priority: 2,
    summary: 'Reducing time-to-first-token and total latency, and deploying AI backends safely.',
    intuition: 'Stream everything, shrink prompts, parallelise independent calls, cache prefixes, use smaller models for non-critical steps, and move slow work off the request path. Deploy like any service: containers, health checks, config-driven models, canary releases.',
    pitfalls: 'Sequential tool calls that could be parallel; serverless cold starts plus long streams hitting platform timeouts; hard-coded model names; no cost alerts.',
    notes: '### Checklist\n- Measure TTFT, tokens/sec, p95 total latency per route.\n- Parallel tool calls and Task.WhenAll / Promise.all for independent retrievals.\n- Speculative/early UI: show retrieved sources before the answer completes.\n- Deploy: Docker multi-stage, env-based secrets (Key Vault), readiness probes, autoscale on concurrency not CPU.\n- Feature flags for model/prompt rollout; instant rollback.\n- Budget alerts on provider spend.',
  },

  // ---------------- 10. AI-Assisted Engineering ----------------
  {
    category: C10,
    title: 'Agentic Coding Workflows: Copilot Agent, Claude Code & Cursor',
    difficulty: 'Easy',
    priority: 1,
    summary: 'Using coding agents effectively: planning, context files, tool permissions, verification.',
    intuition: 'Treat the agent like a fast junior engineer with no memory: give it clear goals, the files that matter, repo conventions (AGENTS.md / CLAUDE.md / copilot-instructions.md), and a way to verify its work (tests, type-check, lint).',
    pitfalls: 'Accepting large diffs unread; letting the agent run destructive commands unapproved; vague prompts; no tests so nothing proves the change works.',
    notes: '### Workflow\n1. Explore & plan first (ask for a plan, review it).\n2. Small, scoped tasks; commit often so you can revert.\n3. Keep an AGENTS.md with build/test commands, architecture, conventions, gotchas.\n4. Let it run tests/typecheck and iterate on failures.\n5. Review diffs like a PR; check security-sensitive code by hand.\n6. Use sub-agents / parallel sessions for independent tasks; use MCP servers for docs, DB schema, issue tracker.',
  },
  {
    category: C10,
    title: 'Spec-Driven Development & Reviewing AI-Generated Code',
    difficulty: 'Medium',
    priority: 2,
    summary: 'Writing specs and acceptance tests that guide agents, and a review checklist for AI-written code.',
    intuition: 'The clearer the spec and tests, the better the agent. Write requirements, edge cases and acceptance criteria first; ask the agent to implement against them. Review for correctness, security, and maintainability, not just whether it compiles.',
    pitfalls: 'Hallucinated APIs and packages (verify they exist); subtle logic bugs that pass shallow tests; copy-pasted insecure patterns; unnecessary abstractions and dead code.',
    notes: '### Review checklist\n- Does it do what the spec says, including failure paths?\n- Are inputs validated, queries parameterised, authz enforced?\n- Are dependencies real, maintained and licensed?\n- Tests meaningful (not asserting the implementation)?\n- Concurrency, resource disposal, error handling, logging.\n- Performance traps (N+1, unbounded loops, allocations).\n- Keep PRs small; require human sign-off.',
  },
  {
    category: C10,
    title: 'Testing AI Features & Using AI to Write Tests',
    difficulty: 'Medium',
    priority: 2,
    summary: 'How to unit/integration test non-deterministic LLM code and leverage agents for test generation.',
    intuition: 'Test the deterministic shell with ordinary tests (fake IChatClient returning canned responses), and the model behaviour with evals. Record/replay LLM responses for stable CI.',
    pitfalls: 'Live LLM calls in unit tests (flaky, slow, costly); snapshot-testing free-text; tests that only check that "something" was returned.',
    notes: '### Layers\n- Unit: tool functions, prompt builders, parsers, routers with a fake model client.\n- Integration: WebApplicationFactory with fake provider; contract tests for tool schemas.\n- Evals: nightly job on real models with thresholds.\n- Property/fuzz: injection strings, huge inputs, unicode.\n- AI-generated tests: ask for edge cases and mutation-style checks, then verify they fail when the code is broken.',
  },

  // ---------------- 11. AI System Design ----------------
  {
    category: C11,
    title: 'Design an Enterprise RAG Chatbot',
    difficulty: 'Hard',
    priority: 1,
    summary: 'System design walk-through for a secure, multi-tenant, citation-backed knowledge assistant.',
    intuition: 'Clarify scope (sources, users, freshness, ACLs, languages, SLAs), then design: ingestion pipeline, permission-aware index, retrieval + rerank, generation with citations, feedback and evals, observability, cost controls.',
    pitfalls: 'Forgetting document-level permissions; no freshness/incremental indexing story; no evaluation plan; skipping failure modes (no answer found, provider outage).',
    notes: '### Components\n- Connectors (SharePoint, Confluence, Drive, DB) -> queue -> parser/chunker -> embedder -> vector + keyword index with ACL metadata.\n- Query service: auth -> query rewrite -> hybrid retrieve with ACL filter -> rerank -> LLM -> citations.\n- Caches: embeddings, retrieval, prompt prefix.\n- Async: re-index on change events, content-hash dedupe.\n- Quality: offline evals, online thumbs, sampled review.\n- Scale numbers: docs count, chunks (docs x chunks/doc), QPS, tokens/query, cost/day.\n- Failure: fallback model, "I don\'t know" path, degraded keyword-only search.',
  },
  {
    category: C11,
    title: 'Design a Coding Agent',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Architecture for an agent that reads a repo, edits files, runs tests and opens PRs safely.',
    intuition: 'Core loop with tools (read/search/edit/run), a sandboxed workspace per task, repo indexing for retrieval, test-driven verification, and strict permission/approval layers.',
    pitfalls: 'Running in the user\'s real environment with secrets; unbounded loops; giant file reads blowing the context; no way to resume or audit.',
    notes: '### Design\n- Task API + queue; worker spins up an ephemeral container with the repo checked out.\n- Tools: search (ripgrep + embeddings), view file ranges, apply patch, run command (allow-list), run tests.\n- Context management: repo map, compaction, notes file.\n- Verification loop: tests/lint/typecheck; stop when green or budget hit.\n- Output: branch + PR with explanation; human review required.\n- Observability: full trajectory trace; cost per task; success rate by task type.\n- Security: no network except package mirror, scoped Git token, secret scanning.',
  },
  {
    category: C11,
    title: 'Design an AI Customer Support Agent with Human Handoff',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Agent that resolves tickets using knowledge base and account tools, escalating when unsure.',
    intuition: 'Route intent first, ground answers in KB via RAG, use authenticated read tools for account info, require confirmation for actions (refund, cancel), and hand off to a human with full context when confidence is low or policy requires.',
    pitfalls: 'Letting the agent promise refunds it cannot grant; no escalation triggers; losing conversation context at handoff; measuring only deflection rate instead of resolution quality and CSAT.',
    notes: '### Flow\nIntent router -> (FAQ: RAG) | (Account: tools) | (Action: policy engine + approval) | (Escalate: summary + transcript to human queue).\n\n### Metrics\nResolution rate, escalation rate, CSAT, time-to-resolution, hallucination/policy-violation rate, cost per ticket.\n\n### Safeguards\nPolicy as code (refund limits), audit log, PII redaction, injection-resistant ticket ingestion, tone guidelines.',
  },
  {
    category: C11,
    title: 'Design an LLM Gateway / AI Platform',
    difficulty: 'Hard',
    priority: 3,
    summary: 'Shared internal service giving teams governed access to many models.',
    intuition: 'A single choke point for auth, routing, quotas, caching, safety filters and observability across providers, exposing a stable OpenAI-compatible API to internal teams.',
    pitfalls: 'Gateway becoming a latency/availability bottleneck; per-team cost attribution missing; logging sensitive prompts in clear text.',
    notes: '### Features\n- Auth (service identity / JWT) and team budgets.\n- Model catalog, routing and fallback policies, A/B.\n- Token-aware rate limiting and quotas.\n- Request/response cache, prompt-cache hints.\n- Guardrails/PII redaction plugins.\n- Usage metering, chargeback dashboards, audit.\n- Streaming passthrough, high availability (stateless, horizontal scale), config hot-reload.',
  },

  // ---------------- 12. Capstone Projects ----------------
  {
    category: C12,
    title: 'Capstone 1: RAG Q&A over Your Own Docs (Next.js + pgvector)',
    difficulty: 'Hard',
    priority: 1,
    summary: 'Build and deploy a full-stack RAG app with ingestion, hybrid retrieval, streaming chat, citations and an eval suite.',
    intuition: 'Goal: prove end-to-end skill. Deliver ingestion CLI, Postgres + pgvector schema, hybrid search with reranking, streaming chat UI with citations, auth + per-user limits, and a 50-question eval run in CI.',
    pitfalls: 'Skipping the eval set; hard-coding keys; no README showing architecture and trade-offs (recruiters read this).',
    notes: '### Definition of done\n- [ ] Ingest PDFs/Markdown with metadata and content-hash dedupe\n- [ ] Hybrid retrieval + rerank, ACL filter\n- [ ] Streaming Next.js chat with source citations\n- [ ] Tracing (Langfuse/OpenTelemetry) and cost per request\n- [ ] Eval script: recall@k, faithfulness; results in README\n- [ ] Dockerfile + deployment\n- [ ] Write-up: architecture diagram, decisions, failure cases',
  },
  {
    category: C12,
    title: 'Capstone 2: Tool-Using Agent with a Custom MCP Server (.NET or TypeScript)',
    difficulty: 'Hard',
    priority: 1,
    summary: 'Expose a real backend (orders, tickets, or this app\'s topics) as an MCP server and drive it with an agent that has approvals and audit logs.',
    intuition: 'Shows protocol knowledge, secure tool design and agent engineering together: scoped tools, schema validation, human approval for writes, trace of every call.',
    pitfalls: 'Exposing raw SQL as a tool; no auth on the HTTP transport; giving write tools without confirmation.',
    notes: '### Definition of done\n- [ ] MCP server with 4+ tools and 1+ resource (stdio and Streamable HTTP)\n- [ ] Authz per user; input validation; idempotent writes\n- [ ] Agent client with max-steps/budget and approval step for mutations\n- [ ] Audit log + OpenTelemetry traces\n- [ ] Unit tests with fake model; 20-case agent eval\n- [ ] Demo video/GIF and README',
  },
  {
    category: C12,
    title: 'Capstone 3: Multi-Agent Research Assistant with Evals & Tracing',
    difficulty: 'Hard',
    priority: 2,
    summary: 'Orchestrator that plans, fans out researcher agents, synthesises a cited report, and is measured by an eval harness.',
    intuition: 'Demonstrates orchestration, context engineering (sub-agents return condensed findings), long-running job design, and measurable quality/cost tradeoffs versus a single-agent baseline.',
    pitfalls: 'No single-agent baseline to compare; uncited claims; unbounded fan-out cost.',
    notes: '### Definition of done\n- [ ] Planner + parallel researcher workers + synthesiser/critic\n- [ ] Job API with progress streaming and cancellation\n- [ ] Budgets (steps, tokens, time) enforced\n- [ ] Report with citations; citation-check step\n- [ ] Eval harness comparing single vs multi-agent on quality, cost, latency\n- [ ] Trace screenshots and lessons-learned section in README',
  },
];

export const AI_SEED_TOPICS: SeedTopic[] = RAW.map((r, i) => ({
  id: `ai-${slugify(r.title).slice(0, 60)}`,
  pillar: 'ai_agentic',
  category: r.category,
  title: r.title,
  slug: slugify(r.title),
  difficulty: r.difficulty,
  priority: r.priority,
  // Spread topics evenly across the 90-day calendar
  day_target: Math.max(1, Math.round(((i + 1) / RAW.length) * 90)),
  external_url: r.url,
  summary: r.summary,
  key_intuition: r.intuition,
  pitfalls: r.pitfalls,
  notes: `### ${r.title}\n- Category: ${r.category}\n- Difficulty: ${r.difficulty}\n\n${r.notes}`,
  code_snippet: r.code,
  status: 'pending',
  confidence: 1,
  box: 1,
}));
